version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: waiting_room
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  api-gateway:
    image: node:20
    working_dir: /app
    volumes:
      - ../services/api-gateway:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
  user-service:
  build:
    context: ../services/user-service
    dockerfile: Dockerfile
  ports:
    - "4000:3000"
  depends_on:
    - postgres
    - redis

volumes:
  pgdata:

